### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by schmidtgo** [UltimaPhoenix/luceneappengine#5]
Hi UltimaPhoenix! I tried to set up LAE using your IndexServlet example. When I want to index a text I get the following exception with the preceding log entries:
```
212646 [408602833@qtp-786887171-8] DEBUG com.googlecode.luceneappengine.GaeLockFactory  - Locking Lock 'Key<?>(LuceneIndex("orders")).write.lock'.
212699 [408602833@qtp-786887171-8] DEBUG com.googlecode.luceneappengine.Segment  - Created Hunk 'orders-pending_segments_1-1'.
212715 [408602833@qtp-786887171-8] DEBUG com.googlecode.luceneappengine.GaeDirectory  - Created segment 'pending_segments_1'.
212793 [408602833@qtp-786887171-8] DEBUG com.googlecode.luceneappengine.GaeLockFactory  - Unlocking Lock 'write.lock'.
Aug 19, 2015 8:57:46 PM com.google.api.server.spi.SystemService invokeServiceMethod
Schwerwiegend: exception occurred while calling backed method
java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.util.StringHelper
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:190)
	at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
	at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:65)
	at org.apache.lucene.index.DocumentsWriterPerThread.<init>(DocumentsWriterPerThread.java:181)
	at org.apache.lucene.index.DocumentsWriter.ensureInitialized(DocumentsWriter.java:397)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:453)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1363)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1142)
	at de.Package.Order.lucene.IndexWorker.addDoc(IndexWorker.java:81)
	at de.Package.Order.lucene.IndexWorker.indexText(IndexWorker.java:66)
	at com.google.cloud.backend.spi.QueryOperations.addQuerySubscriber(QueryOperations.java:280)
	at com.google.cloud.backend.spi.QueryOperations.list(QueryOperations.java:100)
	at com.google.cloud.backend.spi.EndpointV1.list(EndpointV1.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.appengine.tools.development.agent.runtime.Runtime.invoke(Runtime.java:130)
	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:359)
	at com.google.api.server.spi.SystemServiceServlet.execute(SystemServiceServlet.java:113)
	at com.google.api.server.spi.SystemServiceServlet.doPost(SystemServiceServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:502)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.util.StringHelper
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:190)
		at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
		at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:65)
		at org.apache.lucene.index.SegmentInfos.write(SegmentInfos.java:469)
		at org.apache.lucene.index.SegmentInfos.prepareCommit(SegmentInfos.java:731)
		at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:4319)
		at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2763)
		at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2866)
		at org.apache.lucene.index.IndexWriter.shutdown(IndexWriter.java:972)
		at org.apache.lucene.index.IndexWriter.close(IndexWriter.java:1015)
		at de.Package.Order.lucene.IndexWorker.indexText(IndexWorker.java:67)
		... 50 more

Since I was using App Engine 1.9.21 and found the following code on "https://cloud.google.com/appengine/docs/java/gettingstarted/ui_and_code", I updated to 1.9.25 but that did not help anyway:
Note: If you get a runtime error when you first visit localhost:8080, referring to a restricted class, for example, java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets is a restricted class., check the settings for guestbook/pom.xml. The App Engine version must be set to the most recent App Engine SDK version: 1.9.25.
```
Any idea what the reason could be?

Thanks in advance,
Marco

**Comment by UltimaPhoenix** [comment]
Probably you need to add some missing dependencies to your project. Did you add `lucene-core` dependency to your project?
Check the [configuration instructions on the wiki](https://github.com/UltimaPhoenix/luceneappengine/wiki/Usage-and-Configuration) or start from [luceneappengine example sources](https://github.com/UltimaPhoenix/lucene-appengine-examples).

**Comment by schmidtgo** [comment]
I think it might result from my project not being set up properly for use with Maven. I am not really used to it by now and tried to add the luceneappengine functionality to an existing GAE project. Should this work anyway when adding the libraries, configuring the build path, modifiying the web.xml and appengine-web.xml properly?

**Comment by UltimaPhoenix** [comment]
Yes, LAE is not bonded to maven. It is possible to do it manually but you need to add at least the dependencies specified in [TechnologyStack](https://github.com/UltimaPhoenix/luceneappengine/wiki/Technology-Stack). I can improve the wiki by adding "how to do it manually".

**Comment by UltimaPhoenix** [comment]
This problem happens also if you don't follow the [compatibility matrix](https://github.com/UltimaPhoenix/luceneappengine/wiki/Versions)
