### ISSUE TITLE
java.lang.NoClassDefFoundError: java.nio.file.Paths is a restricted class.

### ISSUE THREAD

**Issue by Alchemist0823** [UltimaPhoenix/luceneappengine#6]
```
com.google.api.server.spi.SystemService invokeServiceMethod: exception occurred while calling backend method
java.lang.NoClassDefFoundError: java.nio.file.Paths is a restricted class. Please see the Google App Engine developer's guide for more details.
	at java.nio.file.Paths.<clinit>(Paths.java)
	at org.apache.lucene.util.StringHelper.<clinit>(StringHelper.java:260)
	at org.apache.lucene.index.DocumentsWriterPerThread.<init>(DocumentsWriterPerThread.java:181)
	at org.apache.lucene.index.DocumentsWriter.ensureInitialized(DocumentsWriter.java:397)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:453)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1350)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1138)
	at com.goodi.backend.search.IndexSearchService.index(IndexSearchService.java:39)
	at com.goodi.backend.ActionEndpoint.postQuestion(ActionEndpoint.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:44)
	at com.google.api.server.spi.SystemService.invokeServiceMethod(SystemService.java:363)
	at com.google.api.server.spi.SystemServiceServlet.execute(SystemServiceServlet.java:113)
	at com.google.api.server.spi.SystemServiceServlet.doPost(SystemServiceServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.util.StringHelper
```

**Comment by UltimaPhoenix** [comment]
Check if the `WEB-INF/appengine-web.xml` is properly configured following the [instructions](https://github.com/UltimaPhoenix/luceneappengine/wiki/Usage-and-Configuration).

**Comment by aabdolla** [comment]
I am currently running into this problem trying to use certain suggestors.

I am mainly copying the examples from here:

https://github.com/edng/lucene4_cookbook_examples/blob/master/src/main/java/org/edng/lucene4/example/AutoSuggestTest.java

Of course I am changing the Directory to GaeDirctory but I am getting this error when the suggestor is trying to build the dictionary like on line 63 of the AutoSuggestTest.

I have successfully used the SpellChecker before but it indexes the dictionary a different way than the suggestors:

`try (GaeDirectory directory = new GaeDirectory(indexPhraseName); GaeDirectory suggestDirectory = new GaeDirectory(indexPhraseSuggestionName)) {
			SpellChecker phraseRecommender = new SpellChecker(suggestDirectory);
	
			IndexReader reader = DirectoryReader.open(directory);
			phraseRecommender.indexDictionary(new LuceneDictionary(reader, "title"), getIndexWriterConfig(new StandardAnalyzer()), true);
			phraseRecommender.close();
			reader.close();
		} catch (LockObtainFailedException e) {
			request.setError("Cannot acquire lock to the :'" + indexPhraseName + "' or '" + indexPhraseSuggestionName + "'. Other indexing operation are executing please try again later.");
		} catch (IOException e) {
			request.setError("IO exception:'" + indexPhraseName + "' or '" + indexPhraseSuggestionName + "', cause:" + e.getMessage());
		}`

Any ideas?

**Comment by UltimaPhoenix** [comment]
Your problem is different from the one reported before. Can you create a dedicated issue for it please?

**Comment by aabdolla** [comment]
Yep! Sorry about that. New issue created. Thanks for taking a look!

**Comment by UltimaPhoenix** [comment]
The original issue related to the `org.apache.lucene.util.StringHelper` happens also if you don't follow the [compatibility matrix](https://github.com/UltimaPhoenix/luceneappengine/wiki/Versions).
